Regd 163 hex
RegulomeDB/regulome-ui pull request #53
Opened 2024-04-25 20:19 UTC by mingjiecn

What I did in this ticket:
1. since hex color does not have exactly the same match in tailwind, I try to replace as much hex color with tailwind color as possible and also tailwind color is more human readable.
2. previously we use green color gradient for tissue specific score, but the darker green color can also seems more black, which cause confusion about the intensity. So I change it to blue to green gradient to avoid really dark green color.

2024-04-25 22:30 UTC, forresttanaka requested changes
Nothing major. I think mostly the bitwise OR should change to logical OR, to make sure it doesn’t cause issues in the future. I didn’t see anything about the gradient.

2024-04-25 22:30 UTC, forresttanaka commented on components/human-body-parts.js
> +    organFilters.includes(organName) | highlightedOrgans?.includes(organName)
I know this was there before, but this should use the double `||` instead of the single bitwise `|`. For boolean operands it makes no difference, but the double is more correct. Same for below.

2024-04-25 22:30 UTC, forresttanaka commented on components/snps-diagram.js
> +                    // opacity={item.rect.opacity}
Delete?

2024-04-25 22:30 UTC, forresttanaka commented on components/accessibility-chart.js
> +        backgroundColor: colors.cyan[700],
I couldn’t find documentation from Tailwind about this. Is this different from just using `bg-cyan-700`?

2024-04-26 14:16 UTC, mingjiecn commented on components/human-body-parts.js
> +    organFilters.includes(organName) | highlightedOrgans?.includes(organName)
oops, my bad

2024-04-26 14:21 UTC, mingjiecn commented on components/accessibility-chart.js
> +        backgroundColor: colors.cyan[700],
`bg-cyan-700` will not work here: https://stackoverflow.com/questions/73384596/use-custom-tailwind-color-names-as-inputs-to-chart-js-backgroundcolor-of-chart

2024-04-26 14:55 UTC, forresttanaka approved these changes

2024-04-26 14:58 UTC, forresttanaka commented on components/accessibility-chart.js
> +        backgroundColor: colors.cyan[700],
OK, I still don’t understand why the Tailwind parser can’t see Tailwind class names here, but I’ll have to take it on faith for now. That stackoverflow thread eventually settled on a different solution. I see lots of people importing tailwind/colors into their tailwind.config.js which makes total sense to me, and is the one example I could find in official Tailwind docs.

2024-04-26 15:00 UTC, mingjiecn commented on components/accessibility-chart.js
> +        backgroundColor: colors.cyan[700],
hmmm, maybe import color to config is simpler. I can try that and let you know.

2024-04-26 15:37 UTC, mingjiecn commented on components/accessibility-chart.js
> +        backgroundColor: colors.cyan[700],
OK, anther way is to define the colors in config theme colors, then reference the config values: https://tailwindcss.com/docs/configuration#referencing-in-java-script. or here: https://github.com/tailwindlabs/tailwindcss/discussions/11860. It is more useful if you want to use customized colors instead of the default colors tailwind provided. For me since I just need the default colors then import colors is good enough and simpler.

2024-04-26 15:47 UTC, forresttanaka commented on components/accessibility-chart.js
> +        backgroundColor: colors.cyan[700],
OK. Do you know why Tailwind can’t see things like `bg-cyan-700` in this file? That’s the part I don’t understand.

2024-04-26 16:40 UTC, mingjiecn commented on components/accessibility-chart.js
> +        backgroundColor: colors.cyan[700],
My feeling is that even though this field called `backgroundColor `, it is not a real style for background. It only needs the color(without prefix `bg-`) then different styles are used in this color.

2024-04-26 16:40 UTC, merged