REGD-121-chipdata
RegulomeDB/regulome-ui pull request #9
Opened 2023-08-31 15:57 UTC by mingjiecn

What did I do in this ticket:
1. add some example input for query form
2. adjust min distance between labels for snp diagram since I use bigger font
3. add search page header for search page. Click the button will switch views. Right now there are three view links in the header, will add more when create more views.
4. add chip data view. Add chip data table and ship data bar chart into chip data view.
5. add a blank accessibility data view component. Just for testing view switch.
6. create score data view area for displaying data item two in a row.

2023-08-31 20:20 UTC, forresttanaka requested changes
Looks like some good functionality here. Most of my comments are suggestions only, or are arguable, but found a couple errors.

With most of my days filled with code reviews, it really helps me take less time when the code is documented so I at least know what the purpose of functions or sections of functions are, and I suggest it helps you a few months from now after you forget what your code does. At least, this happens to me. We have several cases of code in encoded that we don’t know why it’s there, because the person who wrote it didn’t remember and didn’t comment it.

2023-08-31 20:20 UTC, forresttanaka commented on components/accessibility-view.js
> + * This is the view for diasplay accessibility data for a variant.
`display`

2023-08-31 20:20 UTC, forresttanaka commented on components/accessibility-view.js
> +}
Impressed by you impelementing a custom hook — something a lot of devs don’t even think of using. Since you don’t use this custom hook anywhere else, make sure you can defend your use of it instead of just putting this code directly in `AccessibilityDataView`. Custom hooks are great for sharing React state and functionality among different components, but their utility gets reduced if you only use it in one component.

2023-08-31 20:20 UTC, forresttanaka commented on components/accessibility-view.js
> +  ) : null;
You can shorten this to:
```
return showData && (<React.Fragment>…</ReactFragment>)
```
…just to save a little typing (functionally nearly identical), and I think it makes the code look cleaner. And in these cases you can use `<>…</>` instead of `<React.Fragment></React.Fragment>`, but that’s personal preference — functionally identical.

2023-08-31 20:20 UTC, forresttanaka commented on components/chip-data-bar-chart.js
> +  console.log(counts);
You probably want to remove this? Would also be nice to see a description of what `counts` basically looks like at the end.

2023-08-31 20:20 UTC, forresttanaka commented on components/chip-data-bar-chart.js
> +  });
This is a simple case for `_.sortBy`.

2023-08-31 20:20 UTC, forresttanaka commented on components/chip-data-bar-chart.js
> +  };
Most of the section up through here looks like kind of a blur of code. That might be kind of OK if I was asked to maintain this as I could run it and console.log things to see how they work, but the lack of description makes code review take time and be not so useful to you.

2023-08-31 20:20 UTC, forresttanaka commented on components/chip-data-table.js
> +    sorter: (source) => Number(source.start),
Nice. We don’t often get a chance to use `sorter`.

2023-08-31 20:20 UTC, forresttanaka commented on components/chip-data-table.js
> +    ),
Just confirming, `source.dataset` is an external link? I don’t know what it is. If it’s an internal link, then this should use the `<Link>` component.

2023-08-31 20:20 UTC, forresttanaka commented on components/chip-data-view.js
> +});
Would you be able to describe how this works? If I was asked to fix issues with this, I wouldn’t even know why we need this at all, and I’d feel compelled to remove it in favor of a regular import, like I ended up doing successfully as a test with igvf-ui edit-func.

And I don’t mean describe it here. But maybe I should research this myself. I never found a reason to use it, so I’m not at all sure about it.

2023-08-31 20:20 UTC, forresttanaka commented on components/chip-data-view.js
> +}
Like the other, make sure you can justify the custom hook instead of just using this code directly in `ChipDataView`, as this is the only place you use it.

2023-08-31 20:20 UTC, forresttanaka commented on components/chip-data-view.js
> +  return showChipData ? (
Another good place for the `return showChipData && <>…</>` mechanism. You don’t _have_ to, but it’s certainly common and clean.

2023-08-31 20:20 UTC, forresttanaka commented on components/score-view-data-area.js
> +  value: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
I haven’t seen many people aside from me use `oneOfType` — nice! It can catch some good problems.

2023-08-31 20:20 UTC, forresttanaka commented on components/search-page-header.js
> +}
Again, make sure you an justify this. And I don’t mean to justify it to me here, but just to have the ability to explain why you use a custom hook in only one place. Maybe you expect to need it in other places in the future, or it just helps you keep things clear in your head.

2023-08-31 20:20 UTC, forresttanaka commented on components/search-page-header.js
> +  }
If you use a conditional expression to assign these classes to `className`, you avoid assigning two different values to the same variable. That will increase this code’s performance by 0.000000001%. But no, it’s just unusual to see this operation this way. Alternatively, `let` and `if…else` also avoids assigning two different values to the same variable.

2023-08-31 20:20 UTC, forresttanaka commented on components/search-page-header.js
> +  }
Since you have the same code in both components, this might provide a good place to put this code in a shared function that takes `queryString` and returns `className`. Especially with Tailwind CSS className strings, I try to avoid repeating them in different places because it’s so easy to change one and forget to change the other, and a shared function helps.

2023-08-31 20:20 UTC, forresttanaka commented on components/search-page-header.js
> +};
Reading all of this now, could both of these components get combined into one? They only differ in the button label and text, and editPath. I could see, for documentation purposes, preserving these two components but making them stubs that call a shared component that parameterizes their differences, which could come down to just the label, text, and editPath if you still extract the top five lines into a separate function. It‘s arguable because these aren’t that big, in fact not as big as what I type here, but it seems a shame to have two components that do so much similarly.

2023-08-31 20:20 UTC, forresttanaka commented on components/snps-diagram.js
> +const MIN_DISTANCE_BETWEEN_LABELS = 94;
Yay! Converting these to constants has already paid for itself.

2023-08-31 20:20 UTC, forresttanaka commented on pages/query.js
> +              </div>
You can also make the `<span>` elements `<div>` elements because they all exist within a `flex` div. That could help with vertical alignment issues, though if you don’t have any of those issues, it doesn‘t really matter.

2023-08-31 20:20 UTC, forresttanaka commented on pages/search.js
> +}
It doesn’t look like you use this custom hook anywhere? It doesn’t generate an ESLint error for me for some reason, but I literally don’t see the string `useScore` anywhere else.

2023-08-31 20:20 UTC, forresttanaka commented on pages/search.js
> +  const [showSoreView, setShowScoreView] = useState(true);
`showScoreView`

2023-09-01 13:44 UTC, mingjiecn commented
> Looks like some good functionality here. Most of my comments are suggestions only, or are arguable, but found a couple errors.
> 
> With most of my days filled with code reviews, it really helps me take less time when the code is documented so I at least know what the purpose of functions or sections of functions are, and I suggest it helps you a few months from now after you forget what your code does. At least, this happens to me. We have several cases of code in encoded that we don’t know why it’s there, because the person who wrote it didn’t remember and didn’t comment it.

Thanks, Forrest! I will try to doc as much as possible.

2023-09-01 13:46 UTC, mingjiecn commented on components/accessibility-view.js
> +}
Didn't realize that I don't need a custom hook. Thanks for the explanation!

2023-09-01 14:31 UTC, mingjiecn commented on components/chip-data-table.js
> +    ),
Yes those are encode links, not internal. Thanks for checking!

2023-09-01 14:43 UTC, mingjiecn commented on components/chip-data-view.js
> +});
added

2023-09-01 15:00 UTC, mingjiecn commented on components/search-page-header.js
> +};
You are absolutely right.

2023-09-01 17:14 UTC, forresttanaka approved these changes
💙 Awesome! The new documentation helps a _ton_. I just have one comment misspelling that I have no problem if you let it go.

2023-09-01 17:14 UTC, forresttanaka commented on components/chip-data-view.js
> + * This is the view for diasplay ChIP-seq data for a variant.
“display”

2023-09-01 23:52 UTC, mingjiecn commented on components/chip-data-view.js
> + * This is the view for diasplay ChIP-seq data for a variant.
will fix it first

2023-09-01 23:59 UTC, merged